version: '3.1'

services:
  WebAPI:
    image: webapitemplate
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    volumes:
      - ./loggs:/app/Loggs
    ports:
      - 8082:80
    links:
      - db

  db:
    image: mariadb:10.3.9
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysqlmysql
    environment:
      MYSQL_ROOT_PASSWORD: webapi
      MYSQL_DATABASE: webapi
      MYSQL_USER: webapi
      MYSQL_PASSWORD: webapi

  adminer:
    image: adminer
    links:
      - db
    restart: always
    ports:
      - 9090:8080