version: '3.1'

services:
  WebAPI:
    image: webapitemplate
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
      - 8082:80
    links:
      - db

  db:
    image: mariadb:10.2.13
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: webapi
      MYSQL_DATABASE: webapi
      MYSQL_USER: webapi
      MYSQL_PASSWORD: webapi

  adminer:
    image: adminer
    links:
      - db
    restart: always
    ports:
      - 9090:8080